/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WatchLaterRouteImport } from './routes/watch-later'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as AdsIndexRouteImport } from './routes/ads/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as StudioSettingsRouteImport } from './routes/studio.settings'
import { Route as StudioMonetizationRouteImport } from './routes/studio.monetization'
import { Route as StudioContentRouteImport } from './routes/studio.content'
import { Route as StudioCommentsRouteImport } from './routes/studio.comments'
import { Route as StudioAnalyticsRouteImport } from './routes/studio.analytics'
import { Route as ChannelUserIdRouteImport } from './routes/channel.$userId'
import { Route as AdsCreateRouteImport } from './routes/ads/create'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLaterRoute = WatchLaterRouteImport.update({
  id: '/watch-later',
  path: '/watch-later',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMonetizationRoute = StudioMonetizationRouteImport.update({
  id: '/monetization',
  path: '/monetization',
  getParentRoute: () => StudioRoute,
} as any)
const StudioContentRoute = StudioContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCommentsRoute = StudioCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAnalyticsRoute = StudioAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StudioRoute,
} as any)
const ChannelUserIdRoute = ChannelUserIdRouteImport.update({
  id: '/channel/$userId',
  path: '/channel/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsCreateRoute = AdsCreateRouteImport.update({
  id: '/ads/create',
  path: '/ads/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/trending': typeof TrendingRoute
  '/upload': typeof UploadRoute
  '/verify-email': typeof VerifyEmailRoute
  '/watch-later': typeof WatchLaterRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/ads/create': typeof AdsCreateRoute
  '/channel/$userId': typeof ChannelUserIdRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/comments': typeof StudioCommentsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/monetization': typeof StudioMonetizationRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ads/': typeof AdsIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trending': typeof TrendingRoute
  '/upload': typeof UploadRoute
  '/verify-email': typeof VerifyEmailRoute
  '/watch-later': typeof WatchLaterRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/ads/create': typeof AdsCreateRoute
  '/channel/$userId': typeof ChannelUserIdRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/comments': typeof StudioCommentsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/monetization': typeof StudioMonetizationRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/admin': typeof AdminIndexRoute
  '/ads': typeof AdsIndexRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/trending': typeof TrendingRoute
  '/upload': typeof UploadRoute
  '/verify-email': typeof VerifyEmailRoute
  '/watch-later': typeof WatchLaterRoute
  '/welcome': typeof WelcomeRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/ads/create': typeof AdsCreateRoute
  '/channel/$userId': typeof ChannelUserIdRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/comments': typeof StudioCommentsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/monetization': typeof StudioMonetizationRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ads/': typeof AdsIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/leaderboard'
    | '/library'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/rewards'
    | '/settings'
    | '/shorts'
    | '/signup'
    | '/studio'
    | '/subscriptions'
    | '/trending'
    | '/upload'
    | '/verify-email'
    | '/watch-later'
    | '/welcome'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/users'
    | '/admin/videos'
    | '/ads/create'
    | '/channel/$userId'
    | '/studio/analytics'
    | '/studio/comments'
    | '/studio/content'
    | '/studio/monetization'
    | '/studio/settings'
    | '/watch/$videoId'
    | '/admin/'
    | '/ads/'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/leaderboard'
    | '/library'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/rewards'
    | '/settings'
    | '/shorts'
    | '/signup'
    | '/subscriptions'
    | '/trending'
    | '/upload'
    | '/verify-email'
    | '/watch-later'
    | '/welcome'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/users'
    | '/admin/videos'
    | '/ads/create'
    | '/channel/$userId'
    | '/studio/analytics'
    | '/studio/comments'
    | '/studio/content'
    | '/studio/monetization'
    | '/studio/settings'
    | '/watch/$videoId'
    | '/admin'
    | '/ads'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/leaderboard'
    | '/library'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/rewards'
    | '/settings'
    | '/shorts'
    | '/signup'
    | '/studio'
    | '/subscriptions'
    | '/trending'
    | '/upload'
    | '/verify-email'
    | '/watch-later'
    | '/welcome'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/users'
    | '/admin/videos'
    | '/ads/create'
    | '/channel/$userId'
    | '/studio/analytics'
    | '/studio/comments'
    | '/studio/content'
    | '/studio/monetization'
    | '/studio/settings'
    | '/watch/$videoId'
    | '/admin/'
    | '/ads/'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  ShortsRoute: typeof ShortsRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRouteWithChildren
  SubscriptionsRoute: typeof SubscriptionsRoute
  TrendingRoute: typeof TrendingRoute
  UploadRoute: typeof UploadRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WatchLaterRoute: typeof WatchLaterRoute
  WelcomeRoute: typeof WelcomeRoute
  AdsCreateRoute: typeof AdsCreateRoute
  ChannelUserIdRoute: typeof ChannelUserIdRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
  AdsIndexRoute: typeof AdsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-later': {
      id: '/watch-later'
      path: '/watch-later'
      fullPath: '/watch-later'
      preLoaderRoute: typeof WatchLaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/ads/': {
      id: '/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/monetization': {
      id: '/studio/monetization'
      path: '/monetization'
      fullPath: '/studio/monetization'
      preLoaderRoute: typeof StudioMonetizationRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/content': {
      id: '/studio/content'
      path: '/content'
      fullPath: '/studio/content'
      preLoaderRoute: typeof StudioContentRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/comments': {
      id: '/studio/comments'
      path: '/comments'
      fullPath: '/studio/comments'
      preLoaderRoute: typeof StudioCommentsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/analytics': {
      id: '/studio/analytics'
      path: '/analytics'
      fullPath: '/studio/analytics'
      preLoaderRoute: typeof StudioAnalyticsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/channel/$userId': {
      id: '/channel/$userId'
      path: '/channel/$userId'
      fullPath: '/channel/$userId'
      preLoaderRoute: typeof ChannelUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/create': {
      id: '/ads/create'
      path: '/ads/create'
      fullPath: '/ads/create'
      preLoaderRoute: typeof AdsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudioRouteChildren {
  StudioAnalyticsRoute: typeof StudioAnalyticsRoute
  StudioCommentsRoute: typeof StudioCommentsRoute
  StudioContentRoute: typeof StudioContentRoute
  StudioMonetizationRoute: typeof StudioMonetizationRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAnalyticsRoute: StudioAnalyticsRoute,
  StudioCommentsRoute: StudioCommentsRoute,
  StudioContentRoute: StudioContentRoute,
  StudioMonetizationRoute: StudioMonetizationRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  ShortsRoute: ShortsRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRouteWithChildren,
  SubscriptionsRoute: SubscriptionsRoute,
  TrendingRoute: TrendingRoute,
  UploadRoute: UploadRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WatchLaterRoute: WatchLaterRoute,
  WelcomeRoute: WelcomeRoute,
  AdsCreateRoute: AdsCreateRoute,
  ChannelUserIdRoute: ChannelUserIdRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
  AdsIndexRoute: AdsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
